### ISSUE TITLE
Disable default config copying

### ISSUE THREAD

**Issue by craftbyte** [IdentityPython/satosa-docker#3]
At the moment, the default config gets copied to the container and there is no way to disable that. Even if we run a volume for the config for example, the ping_frontend cannot be disabled. Could we make this configurable?

**Comment by niheconomoum** [comment]
The entrypoint script will not overwrite any existing configuration files:

https://github.com/IdentityPython/satosa-docker/blob/90979979396447c8c11401ae13105eab6c36d0e8/docker-entrypoint.sh#L41

You can safely add or mount your own configuration into the container at /etc/satosa.

That said, the entry point script is customizable.  For example, your Dockerfile might look like this:

```dockerfile
FROM satosa
USER root
RUN pip install --no-cache-dir satosa[ldap]==${SATOSA_VERSION}
COPY --chown=satosa:satosa *.yaml /etc/satosa/
COPY --chown=satosa:satosa plugins /etc/satosa/
COPY --chown=satosa:satosa attributemaps /etc/satosa/
COPY custom-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["custom-entrypoint.sh"]
USER satosa:satosa
CMD ["gunicorn","-b0.0.0.0:8080","satosa.wsgi:app"]
```

And your custom-entrypoint.sh script might look like this:

```bash
#!/usr/bin/env bash

. /usr/local/bin/docker-entrypoint.sh

function _start() {
    # if the first arg looks like a flag, assume it's for Gunicorn
    if [ "${1:0:1}" = '-' ]; then
        set -- gunicorn "$@"
    fi

    if [ "${1:0:1}" = '-' ]; then
        docker_setup_env
        # skip docker_create_config and docker_pprint_metadata
        exec "$@"
    fi

    exec "$@"
}

if ! _is_sourced; then
    _start "$@"
fi
```

That custom entry point script preserves the semantics of the original (e.g., `docker run -it --rm satosa bash` starts an unprivileged shell inside the container), but it skips unwanted initialization steps.
